name: Status Badges

on:
  workflow_run:
    workflows: ["Main CI Workflow"]
    branches: [master]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Build Status
        id: build-status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "status=passing" >> $GITHUB_OUTPUT
            echo "color=22B24B" >> $GITHUB_OUTPUT
          else
            echo "status=failing" >> $GITHUB_OUTPUT
            echo "color=E11D21" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate Badges
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          name: build
          label: build
          status: ${{ steps.build-status.outputs.status }}
          color: ${{ steps.build-status.outputs.color }}
          github_token: ${{ secrets.GITHUB_TOKEN }}