name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Lint
        run: pnpm lint
        
      - name: Build
        run: pnpm build
      
      - name: Run tests
        run: pnpm jest --config jest.config.ci.js
        env:
          CI: true
          FIREBASE_PROJECT_ID: mock-project-id
          FIRESTORE_EMULATOR_HOST: localhost:8080
