name: Setup Firebase Mock

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up mock credentials
        id: setup-firebase
        run: |
          mkdir -p ./.firebase
          
          # Create full service account credentials with all required fields
          cat > ./.firebase/mock-credentials.json << EOF
          {
            "type": "service_account",
            "project_id": "mock-project-id",
            "private_key_id": "mock-key-id",
            "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmxxx\\n-----END PRIVATE KEY-----\\n",
            "client_email": "mock-service-account@mock-project-id.iam.gserviceaccount.com",
            "client_id": "123456789012345678901",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mock-service-account%40mock-project-id.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
          EOF
          
          # Create the mocks directory with the new file structure
          mkdir -p ./tests/mocks/firebase
          
          # Copy the credential file to the test mocks directory
          cp ./.firebase/mock-credentials.json ./tests/mocks/firebase/mock-service-account.json
          
          # Ensure legacy path for compatibility
          mkdir -p ./tests/mocks
          cp ./.firebase/mock-credentials.json ./tests/mocks/mock-service-account.json
          
          echo "Completed Firebase mock setup"